version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/www"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    # https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#example-disabling-version-updates-for-some-dependencies
    ignore:
      - dependency-name: "@mapwatch/*"
  - package-ecosystem: npm
    directory: "/packages/rss"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/datamine"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: elm
    directory: "/packages/www"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/electron2"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
