version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/www"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/rss"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/datamine2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: elm
    directory: "/packages/www"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/electron2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10