dist: trusty
# for apt-get. Sadly, we can't use travis's sudo-free apt setup, as wine needs a custom apt repo.
sudo: true
language: node_js
node_js:
  - "8"

# https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html
cache:
  directories:
    - packages/www/elm-stuff/build-artifacts
    - packages/lib/elm-stuff/build-artifacts
    - node_modules/
    - sysconfcpus/

before_install:
  # https://wiki.winehq.org/Ubuntu
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt-get update
  - sudo apt-get install -y xvfb winehq-stable
  - wine --version
  # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # https://github.com/elm/compiler/issues/1473
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/sysconfcpus/bin

install:
  - travis_retry sysconfcpus -n 2 yarn

script:
  - yarn test
  # `yarn build` may also release the electron build, if there's a draft or a tag.
  # https://www.electron.build/configuration/publish#recommended-github-releases-workflow
  #- GH_TOKEN=$GITHUB_TOKEN sysconfcpus -n 2 yarn build
  - GH_TOKEN=$GITHUB_TOKEN yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    repo: mapwatch/mapwatch.github.io
    target-branch: master # github-pages: user pages use the master branch, not gh-pages branch
    local_dir: packages/www/dist/
    github_token: $GITHUB_TOKEN
    #keep_history: true
    on:
      branch: master
