language: node_js

# https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html
cache:
  directories:
    - elm-stuff/build-artifacts

install: 
  - npm install -g elm
  - elm --version
  - travis_retry elm-package install --yes
  # Uncached elm builds take ages. Cached builds are quick, so this should rarely be needed.
  - travis_wait 20

script:
  - ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  #keep_history: true
  on:
    branch: master
