dist: trusty
# for apt-get. Sadly, we can't use travis's sudo-free apt setup, as wine needs a custom apt repo.
sudo: true
services: docker
language: node_js
node_js:
  - "10"

addons:
  apt:
    # an old version of yarn is preinstalled. update it.
    sources:
    - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
      key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - yarn

# https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html
cache:
  directories:
    - packages/www/elm-stuff/build-artifacts
    - node_modules/
    - sysconfcpus/
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - sudo rm /usr/local/bin/yarn   # an old version of yarn is preinstalled. alias didn't work, so let's be more thorough.
  - yarn --version
  - export GH_TOKEN=$GITHUB_TOKEN   # TODO rename me in travis settings
  # https://github.com/elm/compiler/issues/1473
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/sysconfcpus/bin
  - yarn config set workspaces-experimental true

install:
  - travis_retry sysconfcpus -n 2 yarn --frozen-lockfile

script:
  - yarn test
  # `yarn build` may also release the electron build, if there's a draft or a tag.
  # https://www.electron.build/configuration/publish#recommended-github-releases-workflow
  - sysconfcpus -n 2 yarn build --ignore @mapwatch/datamine --ignore @mapwatch/electron2

  #- yarn build:electron2
  # https://www.electron.build/multi-platform-build
  # https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml
  - ENVFILE=`mktemp`
  - env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_' > $ENVFILE
  - |
    docker run --rm \
      --env-file $ENVFILE \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      yarn build:electron2

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

deploy:
  - provider: pages
    skip_cleanup: true
    repo: mapwatch/mapwatch.github.io
    target-branch: master # github-pages: user pages use the master branch, not gh-pages branch
    local_dir: packages/mapwatch.github.io/
    github_token: $GITHUB_TOKEN
    #keep_history: true
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: mapwatch.erosson.org
    region: us-east-1
    local_dir: packages/www/build/
    on:
      branch: master
