# CI build instructions for AWS.
#
# We periodically download poe and build the datmined updates. Github's free CI
# machines don't have the disk space for that, and wipe their disk every run -
# unacceptable for a 30GB clean download. Even free build cache is pretty slow.
# AWS is slightly worse than free, but we can save the download across builds
# and only download the diffs.
#
# Not done yet, but we'll probably start it from a github action:
# https://github.com/aws-actions/aws-codebuild-run-build
#
# The mapwatch aws dashboard:
# https://console.aws.amazon.com/codesuite/codebuild/859469699167/projects/mapwatch-dataminer
#
# Secrets management:
# https://console.aws.amazon.com/systems-manager/parameters/?region=us-east-1&tab=Table
#
# buildspec.yml docs:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

env:
  parameter-store:
    STEAMCTL_USER: mapwatch-dataminer-STEAMCTL_USER
    STEAMCTL_PASSWD: mapwatch-dataminer-STEAMCTL_PASSWD
    STEAMCTL_SECRET: mapwatch-dataminer-STEAMCTL_SECRET

phases:
  install:
    runtime-versions:
      nodejs: latest
      python: latest
    commands:
      - pip install steamctl pexpect
      - yarn --frozen-lockfile
      # - env
  pre_build:
    commands:
      - ( cd packages/datamine-dl && python packages/datamine-dl/steamctl-auth.py )
  build:
    commands:
      # info for the poe-content/ggpk depot
      - ( cd packages/datamine-dl && yarn info.txt )
