version: 1
update_configs:
  - package_manager: elm
    directory: /packages/www
    update_schedule: daily # live is not allowed for elm :(
  - package_manager: javascript
    directory: /packages/www
    update_schedule: live
  - package_manager: javascript
    directory: /packages/rss
    update_schedule: live
  - package_manager: javascript
    directory: /packages/electron2
    update_schedule: live
  - package_manager: javascript
    directory: /packages/datamine
    update_schedule: live
