name: assets-export
on:
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  # windows must run this, not ubuntu, as pypoe/our datamine export depends on packages/datamine/ooz.exe
  fetch:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMCTL_USER }}"
          echo "::add-mask::${{ secrets.STEAMCTL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMCTL_SECRET }}"
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - working-directory: ./packages/datamine-dl
        run: yarn fetch:install
      - working-directory: ./packages/datamine-dl
        env:
          STEAMPULL_USER: ${{ secrets.STEAMCTL_USER }}
          STEAMPULL_PASSWD: ${{ secrets.STEAMCTL_PASSWD }}
          STEAMPULL_SECRET: ${{ secrets.STEAMCTL_SECRET }}
        run: yarn fetch:auth
      - working-directory: ./packages/datamine-dl
        run: yarn fetch

      - working-directory: ./packages/datamine-dl
        run: |
          echo 'STEAM_DEPOT_INFO_NEW<<__EOF__' >> $GITHUB_ENV
          cat info.txt >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - working-directory: ./packages/datamine-dl
        run: |
          echo 'STEAM_DEPOT_INFO_DIFF<<__EOF__' >> $GITHUB_ENV
          (diff info-old.txt info.txt || true) >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      # Stop running here if there's no info.txt differences
      # If PRs ever stop working, we could create an issue instead:
      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  uses: JasonEtco/create-an-issue@v2
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    filename: .github/ggpk-notify-issue-template.md
      #    update_existing: true

      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        working-directory: ./packages/datamine
        run: yarn pypoe:install:ci
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: yarn install --frozen-lockfile
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        working-directory: ./packages/datamine
        run: yarn export
      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] POE content updates'
          title: '[assets-export] POE content updates'
          body: >
            Looks like Path of Exile was patched recently! I've updated mapwatch for you.

            This PR was auto-generated by the [assets-export robot](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Aassets-export).
          labels: automated pr
