name: assets-export
on:
  schedule:
    - cron: "5 1 * * *"
  push:
    branches: [master]
    paths: ["third-party/**"]
  workflow_dispatch:
    inputs:
      force_build:
        description: "force_build: if non-empty, rebuild even if there are no PoE content changes"
        required: false
        default: ''

jobs:
  # windows must run this, not ubuntu, as pypoe/our datamine export depends on packages/datamine/ooz.exe
  fetch:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile
      - run: git submodule update --remote
      # https://stackoverflow.com/a/5143914/2782048
      - run: git diff-index --quiet HEAD -- || echo "PYPOE_JSON_DIFF=1" >> $GITHUB_ENV
      - if: ${{ github.event.inputs.force_build || env.PYPOE_JSON_DIFF != '' }}
        working-directory: ./packages/datamine
        run: yarn dist
      # no need for a website rebuild, merging the pr below will trigger one

      - run: echo "POE_VERSION=`cat packages/datamine/dist/version.txt`" >> $GITHUB_ENV
      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          title: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          body: >
            Looks like Path of Exile was patched recently! I've updated mapwatch for you. New version: ${{ env.POE_VERSION }}.

            This PR was auto-generated by the [assets-export robot](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Aassets-export).
          labels: automated pr
