name: assets-export
on:
  schedule:
    - cron: "5 1 * * *"
  # push:
    # branches: [master]
    # paths: ["packages/datamine/scripts", "packages/datamine/src"]
  workflow_dispatch:
    inputs:
      force-build:
        type: boolean
        description: "Always rebuild and create a PR, even if poe has no updates"

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: yarn install --frozen-lockfile
      - working-directory: ./packages/datamine2
        run: yarn run version

      - run: echo "POE_VERSION=`cat packages/datamine2/dist/version.txt`" | tee $GITHUB_ENV
      - run: git diff
      - run: git diff-index HEAD
      - run: git diff-index --quiet HEAD -- || echo "PYPOE_JSON_DIFF=1" | tee $GITHUB_ENV
      # Run the build only if the poe version number has changed
      - if: ${{ github.event.inputs.force-build == 'true' }}
        run: echo 'build forced'
      - if: ${{ github.event.inputs.force-build == 'true' || env.PYPOE_JSON_DIFF != '' }}
        working-directory: ./packages/datamine2
        run: yarn run dist
      # - run: git diff
      # - run: git diff-index HEAD
      # - run: git diff-index --quiet HEAD -- || echo "PYPOE_JSON_DIFF=1" | tee $GITHUB_ENV
      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      # if nothing's changed - the common case, when poe was not patched - this doesn't create a pr
      - if: ${{ github.event.inputs.force-build == 'true' || env.PYPOE_JSON_DIFF != '' }}
        name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          title: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          body: >
            Looks like Path of Exile was patched recently! I've updated mapwatch for you. New version: ${{ env.POE_VERSION }}. Thanks, [poe-dat-viewer](https://snosme.github.io/poe-dat-viewer/)!

            This PR was auto-generated by the [assets-export robot](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Aassets-export).
          labels: automated pr
