name: ggpk-fetch
on:
  # schedule:
    # - cron: "5 1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #
    # Github docs warn that using self-hosted runners for public repos is dangerous,
    # because pull requests can insert evil code that runs on machines that aren't
    # engineered to defend against it.
    # https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
    #
    # I'm doing so anyway, because I don't use pull request code: this runs
    # periodically, not on push, and always uses the main/master branch.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: yarn install
        run: yarn --frozen-lockfile
      - name: ggpk download
        env:
          GGPK_FETCH_DIR: /media/bigbuild/mapwatch/path-of-exile-ggpk
        run: cd packages/datamine && yarn ggpk:fetch
      # TODO build something with the fetched data
      ## https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      #- name: Create pull request
      #  uses: peter-evans/create-pull-request@v3
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    commit-message: ggpk updates
      #    title: 'ggpk updates'
      #    body: >
      #      This PR is auto-generated by
      #      [create-pull-request](https://github.com/peter-evans/create-pull-request),
      #      via the github actions workflow
      #      [ggpk-fetch](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Aggpk-fetch).
      #    labels: automated pr
