name: ggpk-export
on:
  # schedule:
    # - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  # linux must run `fetch`, as headless steam authentication requires pexpect which has poor windows support.
  # windows must run `export`, as pypoe/our datamine export depends on packages/datamine/ooz.exe.
  #
  # I don't like the complexity of two OSes here... but it works
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMCTL_USER }}"
          echo "::add-mask::${{ secrets.STEAMCTL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMCTL_SECRET }}"
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install steamctl pexpect

      - working-directory: ./packages/datamine-dl
        env:
          STEAMCTL_USER: ${{ secrets.STEAMCTL_USER }}
          STEAMCTL_PASSWD: ${{ secrets.STEAMCTL_PASSWD }}
          STEAMCTL_SECRET: ${{ secrets.STEAMCTL_SECRET }}
        run: python steamctl-auth.py

      - working-directory: ./packages/datamine-dl
        run: yarn fetch

      # stop the build now if steam-depot-info.txt didn't change
      - working-directory: ./packages/datamine-dl
        run: |
          echo 'STEAM_DEPOT_INFO_DIFF<<__EOF__' >> $GITHUB_ENV
          (diff steam-depot-info.txt steam-depot-info-new.txt || true) >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        uses: actions/upload-artifact@v2
        with:
          name: datamine-dl
          path: packages/datamine-dl/dist/**/*
          retention-days: 1
  export:
    needs: fetch
    if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: datamine-dl
          path: packages/datamine-dl/dist
      - run: ls packages/datamine-dl/dist/*
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - working-directory: ./packages/datamine
        run: yarn pypoe:install:ci
      - run: yarn --frozen-lockfile

      - working-directory: ./packages/datamine
        run: yarn export
      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: POE content updates
          title: 'wiki/league-api updates'
          body: >
            Looks like Path of Exile was patched recently. I've updated mapwatch for you.

            This PR is auto-generated by the [datamine-wiki robot](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Adatamine-wiki).
          labels: automated pr
