name: ggpk-notify
on:
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMCTL_USER }}"
          echo "::add-mask::${{ secrets.STEAMCTL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMCTL_SECRET }}"
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      #- uses: actions/setup-node@v1
      #  with:
      #    node-version: 12.x
      #- run: yarn --frozen-lockfile
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install steamctl pexpect
      - working-directory: ./packages/datamine-dl
        env:
          STEAMCTL_USER: ${{ secrets.STEAMCTL_USER }}
          STEAMCTL_PASSWD: ${{ secrets.STEAMCTL_PASSWD }}
          STEAMCTL_SECRET: ${{ secrets.STEAMCTL_SECRET }}
        run: python steamctl-auth.py
      # skip the first line's gibberish
      - working-directory: ./packages/datamine-dl
        env:
          TZ: "Etc/UTC"
        run: yarn info.txt
      # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - working-directory: ./packages/datamine-dl
        run: |
          echo 'STEAM_DEPOT_INFO_NEW<<__EOF__' >> $GITHUB_ENV
          cat steam-depot-info.txt >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - working-directory: ./packages/datamine-dl
        run: |
          echo 'STEAM_DEPOT_INFO_DIFF<<__EOF__' >> $GITHUB_ENV
          (diff steam-depot-info.txt steam-depot-info-new.txt || true) >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ggpk-notify-issue-template.md
          update_existing: true

      #- name: ggpk download
      #  env:
      #    GGPK_FETCH_DIR: /media/bigbuild/mapwatch/path-of-exile-ggpk
      #  run: cd packages/datamine && yarn ggpk:fetch
      # TODO build something with the fetched data
      ## https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      #- name: Create pull request
      #  uses: peter-evans/create-pull-request@v3
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    commit-message: ggpk updates
      #    title: 'ggpk updates'
      #    body: >
      #      This PR is auto-generated by
      #      [create-pull-request](https://github.com/peter-evans/create-pull-request),
      #      via the github actions workflow
      #      [ggpk-fetch](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Aggpk-fetch).
      #    labels: automated pr
