name: push-deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy-www:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn build --ignore @mapwatch/electron2

      # https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: mapwatch/mapwatch.github.io
          BRANCH: master
          FOLDER: packages/mapwatch.github.io/

      # https://github.com/marketplace/actions/s3-sync?version=v0.5.1
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: mapwatch.erosson.org
          AWS_REGION: us-east-1
          SOURCE_DIR: packages/www/build/
  deploy-electron:
    # https://github.com/marketplace/actions/electron-builder-action
    runs-on: windows-latest
    needs: deploy-www
    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          - name: Electron Builder Action
      - run: yarn --frozen-lockfile
      - run: yarn test
      - uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          build_script_name: build:electron2
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
